### PR TITLE
document the build manifest

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
I wasn't completely sure if this should go here, in advanced features or in a section of its own. I think this is very important to know for users when building their first snaps, so I put it here. But because I was too close to this feature, I might be biased and raising it's importance more than I should :)

**Comment by caldav** [comment]
This is excellent to have, but I'm not sure it should be part of making your first snap, as it adds some overhead to a very simple getting started. I'd recommend adding it to the advanced features page, taking into account that the content of the advanced features page needs to be redone. This could be a first step to improve this page.

**Comment by evandandrea** [comment]
It's worth separately documenting. If I'm already using snaps, how do I know to read the getting started guide to create a build manifest?

I'm fine to leave this as-merged for now, but I do not think is necessary to creating your first snap. There is a limit to how many things we will be able to get someone to do when they are new to a platform and have seen no reward from it yet. This feels like something that happens after you get that first release to stable and you're either starting work on that first update or waiting for something to trigger it :)

**Comment by sergiusens** [comment]
Wait, why is this in the "first snap" part? Did I read correctly?

I agree with Evan, this is important when you want to add engineering process around this.
Let's not try and retrofit documentation items into existing topics (if that is the case of what happened here)

**Comment by elopio** [comment]
@kyrofa and I discussed during the sprint that this is not an advanced thing, so the advanced section doesn't sound right either. We were inclined to put it in the "builders" section, because the audit is not really something people will do manually. The manifest will be recorded by the builders, and a tool will inspect the snap and warn when there is a problem.

**Pull request merged**
